# Generated by Django 5.2.8 on 2025-11-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Employee Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='USN'),
        ),
    ]
