# Generated by Django 5.2.8 on 2025-11-06 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_busroute_busstop_routeregistration_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busroute',
            name='driver',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_route', to=settings.AUTH_USER_MODEL),
        ),
    ]
