# Generated by Django 5.2.8 on 2025-11-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_busroute_driver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routeregistration',
            unique_together=set(),
        ),
    ]
