# Generated by Django 5.2.8 on 2025-11-08 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_routeregistration_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('bus_late', 'Is the bus running late?'), ('bus_location', 'Where is the bus now?'), ('route_change', 'Any route changes today?'), ('driver_contact', 'How to contact driver?'), ('fare_query', 'Question about fare'), ('schedule_query', 'Question about schedule'), ('other', 'Other')], max_length=20)),
                ('additional_message', models.TextField(blank=True, help_text='Optional additional details')),
                ('is_answered', models.BooleanField(default=False)),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_queries', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.busroute')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Quick Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('delay', 'Bus Delay'), ('arrival', 'Bus Arrival'), ('route_change', 'Route Change'), ('maintenance', 'Maintenance'), ('emergency', 'Emergency'), ('general', 'General Announcement'), ('query', 'Student Query')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('visible_to_students', models.BooleanField(default=True)),
                ('visible_to_drivers', models.BooleanField(default=True)),
                ('visible_to_admins', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_notifications', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, help_text='Leave blank for system-wide notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.busroute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_notifi_created_f19d5e_idx'), models.Index(fields=['route', 'is_active'], name='core_notifi_route_i_791b8a_idx')],
            },
        ),
    ]
