# Generated by Django 5.2.8 on 2025-11-08 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_quickquery_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickquery',
            name='bus_stop',
            field=models.ForeignKey(blank=True, help_text="Student's bus stop for this query", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='core.busstop'),
        ),
    ]
