# Generated by Django 5.2.8 on 2025-11-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quickquery_bus_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
    ]
