# Generated by Django 5.2.8 on 2025-11-08 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_notification_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=5, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, help_text='Direction in degrees (0-360)', max_digits=5, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the driver is currently sharing location')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='bus_locations', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_locations', to='core.busroute')),
            ],
            options={
                'verbose_name': 'Bus Location',
                'verbose_name_plural': 'Bus Locations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['driver', '-timestamp'], name='core_busloc_driver__4f565c_idx'), models.Index(fields=['route', '-timestamp'], name='core_busloc_route_i_4100bc_idx'), models.Index(fields=['is_active', '-timestamp'], name='core_busloc_is_acti_8014a0_idx')],
            },
        ),
    ]
